// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfxHvF3ZeI015KLPM0Xj8IMBN0xIF4mu8',
    appId: '1:159320239371:web:23ab933a84d6974255860e',
    messagingSenderId: '159320239371',
    projectId: 'md-scents',
    authDomain: 'md-scents.firebaseapp.com',
    storageBucket: 'md-scents.firebasestorage.app',
    measurementId: 'G-QX1JEDNB4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHSTs27IspDljjurZWAWoU-Xn04u8q_yI',
    appId: '1:159320239371:android:dbae97488dbf920f55860e',
    messagingSenderId: '159320239371',
    projectId: 'md-scents',
    storageBucket: 'md-scents.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG6ZN-UzF5QMjkvnfU225mtLypTJo4K70',
    appId: '1:159320239371:ios:3d42269d4212775155860e',
    messagingSenderId: '159320239371',
    projectId: 'md-scents',
    storageBucket: 'md-scents.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG6ZN-UzF5QMjkvnfU225mtLypTJo4K70',
    appId: '1:159320239371:ios:3d42269d4212775155860e',
    messagingSenderId: '159320239371',
    projectId: 'md-scents',
    storageBucket: 'md-scents.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfxHvF3ZeI015KLPM0Xj8IMBN0xIF4mu8',
    appId: '1:159320239371:web:4d3085a0503f31d855860e',
    messagingSenderId: '159320239371',
    projectId: 'md-scents',
    authDomain: 'md-scents.firebaseapp.com',
    storageBucket: 'md-scents.firebasestorage.app',
    measurementId: 'G-FQVP5EM1RT',
  );
}
