// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMIpOk3UVOSdAmhnFbU43G-j5LgWgFicU',
    appId: '1:206439401804:web:9fa132df370b229270a7e9',
    messagingSenderId: '206439401804',
    projectId: 'md-scents-perfumes',
    authDomain: 'md-scents-perfumes.firebaseapp.com',
    storageBucket: 'md-scents-perfumes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ-9aKRfMA45SYpTTG_QRaopzJJYcWFdc',
    appId: '1:206439401804:android:994cf4979181f88c70a7e9',
    messagingSenderId: '206439401804',
    projectId: 'md-scents-perfumes',
    storageBucket: 'md-scents-perfumes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtFMZxoo4a-p3-WAEEw4G5T1S2P3zwe4Y',
    appId: '1:206439401804:ios:a9db57a4335f750b70a7e9',
    messagingSenderId: '206439401804',
    projectId: 'md-scents-perfumes',
    storageBucket: 'md-scents-perfumes.firebasestorage.app',
    iosBundleId: 'com.mdscents.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtFMZxoo4a-p3-WAEEw4G5T1S2P3zwe4Y',
    appId: '1:206439401804:ios:7b27288a51e2ac0970a7e9',
    messagingSenderId: '206439401804',
    projectId: 'md-scents-perfumes',
    storageBucket: 'md-scents-perfumes.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMIpOk3UVOSdAmhnFbU43G-j5LgWgFicU',
    appId: '1:206439401804:web:f43e16522aff31a970a7e9',
    messagingSenderId: '206439401804',
    projectId: 'md-scents-perfumes',
    authDomain: 'md-scents-perfumes.firebaseapp.com',
    storageBucket: 'md-scents-perfumes.firebasestorage.app',
  );
}
